### ISSUE TITLE
Nuxt.js

### ISSUE THREAD

**Issue by anantonton** [HKskn/vue-underscore#1]
Any idea how to use this on nuxt? I cannot find a working guide. Thank you!

**Comment by HKskn** [comment]
You need to define it as a plugin. Please check the following link. https://nuxtjs.org/guide/plugins/

**Comment by anantonton** [comment]
I tried using it as a plugin. 
This is what I did: 
1. Yarn add vue-underscore

2. nuxt.config.js:
    plugins: [
        { src: '~/plugins/underscore', ssr: false },
    ]

3. create a new file /plugins/underscore.js
    import Vue from 'vue'
    import { _ } from 'vue-underscore'
    Vue.use(_)

4. in my pages/index.js
    import { _ } from 'vue-underscore'
    let testArr = [{ id: 1}, { id: 2 }]
    let foundInfo = _.findWhere(testArr, { id: 1 })
    let foundInfo = this.$_.findWhere(testArr, { id: 1 })
    export default {
        data: {
            return {
                foundInfo
            }
        }
    }
5. Call {{ foundData }} (or console.log(foundData))

Didn't work both using _ and this.$_

IF using _ :

Cannot use import statement outside a module

![Screen Shot 2020-04-15 at 11 27 29](https://user-images.githubusercontent.com/20377914/79299738-fed71680-7f0e-11ea-8e08-192eee7753d7.png)

IF using this.$_ (and comment the import { _ } from 'vue-underscore' statement)

Cannot read property '$_' of undefined

![Screen Shot 2020-04-15 at 12 17 18](https://user-images.githubusercontent.com/20377914/79301245-4364b100-7f13-11ea-84cd-c321df2f21a9.png)


this is my package.json dependencies:

"dependencies": {
    "@contentful/rich-text-html-renderer": "^13.4.0",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/dotenv": "^1.4.0",
    "@nuxtjs/markdownit": "^1.2.9",
    "@nuxtjs/moment": "^1.6.0",
    "@nuxtjs/pwa": "^3.0.0-0",
    "contentful": "^7.14.0",
    "moment": "^2.24.0",
    "nuxt": "^2.0.0",
    "underscore": "^1.10.2",
    "vue-underscore": "^0.1.4"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^2.0.0",
    "@nuxtjs/eslint-module": "^1.0.0",
    "@nuxtjs/vuetify": "^1.0.0",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.1.0",
    "eslint": "^6.1.0",
    "eslint-plugin-nuxt": ">=0.4.2",
    "jest": "^24.1.0",
    "vue-jest": "^4.0.0-0"
  }

**Comment by HKskn** [comment]
For the 3rd step do it like below code

```import Vue from 'vue';
import underscore from 'vue-underscore';

Vue.use(underscore);

**Comment by HKskn** [comment]
@anantonton Also I changed readme file to solve misunderstanding.
